language: python
xdist: xenial
python:
  - "3.5"
  - "3.6"

env: PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/tests

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no

install:
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION pytest-cov
  - if [[ "${TRAVIS_PYTHON_VERSION}" == "3.6" ]]; then
        conda install --yes -n testenv flake8;
    fi
  - source activate testenv
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

# Set display for tests involving matplotlib
services:
- xvfb

script:
  - pytest --cov=nscsim tests/unit
  - if [[ "${TRAVIS_PYTHON_VERSION}" == "3.6" ]]; then
        flake8;
    fi

notifications:
  - on_success: never
  - on_failure: never
